stages:
  fetch_data:
    cmd: dvc pull -r myremote
    deps:
      - dvc.yaml

  generate_data:
    cmd: python generate_data.py
    deps:
      - generate_data.py
    outs:
      - data/dummy_sensor_data.csv

  upload_to_drive:
    cmd: dvc push -r myremote
    deps:
      - data/dummy_sensor_data.csv
    outs: []
   
