name: Predictive Maintenance Workflow

on:
  push:
    branches:
      - main

jobs:
  data_acquisition:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install DVC
      run: |
        pip install dvc-gdrive

    - name: Set Git user information
      run: |
        git config --global user.name "mlflops"

    - name: Install Dependencies
      run: pip install -r requirements.txt 

    - name: generate data
      run: |
        python generate_data.py
      

  model_training:
    runs-on: ubuntu-latest
    needs: data_acquisition

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install -r requirements.txt 

    - name: Run MLflow UI
      run: |
        nohup mlflow ui --port 5001 > /dev/null 2>&1 &

    - name: Running Main
      run: |
        [ ! -d ".pkl" ] && python model.py
  
    - name: Stop mlflow
      run: pkill -f "mlflow ui --port 5001"

    - name: Monitoring
      run: |
        python monitor.py

    - name: DockerHub Login
      uses: docker/login-action@v3
      with:
        username: mlflops
        password: mlflops123
        
    - name: Build and push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: mlflops/flask_app:latest




